### ISSUE TITLE
Compile error with GHC 7.10.3/base-4.7

### ISSUE THREAD

**Issue by hvr** [ChrisPenner/rasa#5]
I've noticed that `rasa` fails to compile with base-4.7 even though it declares compatibility with `base >= 4.7`; If you don't want to support GHC 7.8.4, the easiest fix would be to set a lower bound `base >= 4.8`

```
Configuring component lib from rasa-0.1.3
Preprocessing library rasa-0.1.3...
[ 1 of 11] Compiling Rasa.Internal.Extensions ( src/Rasa/Internal/Extensions.hs, /tmp/matrix-worker/1483078889/dist-newstyle/build/x86_64-linux/ghc-7.8.4/rasa-0.1.3/build/Rasa/Internal/Extensions.o )
[ 2 of 11] Compiling Rasa.Internal.Text ( src/Rasa/Internal/Text.hs, /tmp/matrix-worker/1483078889/dist-newstyle/build/x86_64-linux/ghc-7.8.4/rasa-0.1.3/build/Rasa/Internal/Text.o )
[ 3 of 11] Compiling Rasa.Internal.Range ( src/Rasa/Internal/Range.hs, /tmp/matrix-worker/1483078889/dist-newstyle/build/x86_64-linux/ghc-7.8.4/rasa-0.1.3/build/Rasa/Internal/Range.o )

src/Rasa/Internal/Range.hs:135:36:
    Not in scope: ‘sortOn’
    Perhaps you meant one of these:
      ‘sortBy’ (imported from Data.List),
      ‘sort’ (imported from Data.List)

src/Rasa/Internal/Range.hs:151:21:
    Not in scope: ‘foldMap’
    Perhaps you meant one of these:
      ‘ifoldMap’ (imported from Control.Lens),
      ‘foldMapOf’ (imported from Control.Lens),
      ‘foldMapBy’ (imported from Control.Lens)

src/Rasa/Internal/Range.hs:155:21:
    Not in scope: ‘foldMap’
    Perhaps you meant one of these:
      ‘ifoldMap’ (imported from Control.Lens),
      ‘foldMapOf’ (imported from Control.Lens),
      ‘foldMapBy’ (imported from Control.Lens)
```

**Comment by hvr** [comment]
I went ahead and fixed up the meta-data on Hackage in the affected releases:

 - https://hackage.haskell.org/package/rasa-0.1.3/revisions/
 - https://hackage.haskell.org/package/rasa-0.1.1/revisions/
 - https://hackage.haskell.org/package/rasa-0.1.0.0/revisions/

**Comment by ChrisPenner** [comment]
Thanks for this!

Should be fixed in https://github.com/ChrisPenner/rasa/commit/dff384c7c44d0c13ef0f97de97083a5ea5addc44

Let me know if there's anything else I need to do :)
